; ==================================================================================
;  LISTENER'S INITIATES - VANILLA HAIR REMAKE SMP SPELL DISTRIBUTION
; ==================================================================================

; Dark Brotherhood Initiate Male 
Spell = _Uvi_NordHair13Spell|DBInitiate1|NONE|NONE

; Dark Brotherhood Initiate Female 
Spell = _Uvi_NordHair11Spell|DBInitiate2|NONE|NONE

; Lemro Winter-Wave 
Spell = _Uvi_NordHair18Spell|ListenersInitiatesLemro~ListenersInitiates.esp|NONE|NONE

; Brother Crasemir 
Spell = _Uvi_ElfHair05Spell|ListenersInitiatesCrasemir~ListenersInitiates.esp|NONE|NONE

; Brother Vargur 
Spell = _Uvi_NordHair19Spell|ListenersInitiatesVargur~ListenersInitiates.esp|NONE|NONE

; Brother Valerian 
Spell = _Uvi_NordHair04Spell|ListenersInitiatesValerian~ListenersInitiates.esp|NONE|NONE

; Parilla 
Spell = _Uvi_NordHair12Spell|ListenersInitiatesParilla~ListenersInitiates.esp|NONE|NONE

; Alberno 
Spell = _Uvi_NordHair14Spell|ListenersInitiatesAlberno~ListenersInitiates.esp|NONE|NONE

; Fiseya 
Spell = _Uvi_DarkElfHair05Spell|ListenersInitiatesFiseya~ListenersInitiates.esp|NONE|NONE

; Erthor 
Spell = _Uvi_DarkElfHair08Spell|ListenersInitiatesErthor~ListenersInitiates.esp|NONE|NONE

; Grukk 
Spell = _Uvi_OrcHair11Spell|ListenersInitiatesGrukk~ListenersInitiates.esp|NONE|NONE
